home:
  route: public_home
  label: title.home
  icon: '<i class="fas fa-home"></i>'

property:
  route: user_property_index
  label: title.property
  icon: '<i class="fas fa-building"></i>'

#dropdown:
#  label: dropdown
#  children:
#    item1:
#      route: public_home
#      label: item1
#    item2:
#      route: public_home
#      label: item2
#    item3:
#      route: public_home
#      label: item3